### ISSUE TITLE
Can't create project - Exception

### ISSUE THREAD

**Issue by raupes** [NetCoreTemplates/aurelia-spa#3]
When I try to create the project as described "`web new aurelia-spa testproject`" I get the message "`Installing aurelia-spa`" and then.... "`An exception occured during a WebClient request.`"
any help?

**Comment by mythz** [comment]
Should now be resolved with the latest `v0.0.47` of the [web](https://www.nuget.org/packages/web) tool that's been published to NuGet which you can update with:

    $ dotnet tool update -g web

Although it can take up to 30mins for published NuGet packages to be indexed and available for download.
