### ISSUE TITLE
Instructions on running from Visual Studio

### ISSUE THREAD

**Issue by andez2000** [NetCoreTemplates/aurelia-spa#5]
I've followed the instructions which have generated a visual studio solution.  Now what do I do?

I have opened the solution in Visual Studio 2019.  I have ran the `dev` `gulp task`.  When I start to debug this takes me to https://localhost:5001/ with the message "The site can't be reached" with `ERR_CONNECTION_REFUSED` in Chrome.

I've looked at the instructions here:
https://github.com/NetCoreTemplates/aurelia-spa/blob/master/README.md

However, running the `start` `gulp task` and hit `F5` to debug the application, Chrome opens https://localhost:5001/ and I still get the "The site can't be reached" with `ERR_CONNECTION_REFUSED`.

If I navigate to http://localhost:8080 then I see:

![image](https://user-images.githubusercontent.com/16876524/79006175-7ba17380-7b50-11ea-9904-50e5c94d79b1.png)

Although the copyright is somewhat malformed with the dateFormat.

**NOTE:** I still get the `ERR_CONNECTION_REFUSED` when I navigate to http://localhost:8080 when only running the `dev` `gulp task`.

Is there a definitive way to startup from Visual Studio?

Thanks

**Comment by mythz** [comment]
The "malformed copyright" meaning you're viewing an unprocessed static page that's not served by webpack not ServiceStack which you'll need to use during development, i.e. where it's running on https://localhost:5001

Here's what i did:

    $ x new aurelia-spa AureliaSpa

double-click on AureliaSpa.sln to open in VS 2019

Run the `dev` gulp task.

Run the project with `Ctrl+F5` which loads the project on https://localhost:5001

![image](https://user-images.githubusercontent.com/89361/79007821-9692d880-7b8e-11ea-94f8-ecf44a8131c7.png)

Now whilst the `dev` gulp task is running I can make changes to the src files (like app.html) where they'll be automatically reloaded on each save:

![image](https://user-images.githubusercontent.com/89361/79007906-d1950c00-7b8e-11ea-9c11-03d456c5a472.png)

So not sure why it's not working for you, but VS is particularly bad at SPA front end projects, VS Code or Rider is much better. So if you still can't get it running in VS.NET use VS Code to run the npm tasks like `npm run dev` then use VS for the C# back-end.
