### ISSUE TITLE
What is this X you speak of?

### ISSUE THREAD

**Issue by WillSullivan** [NetCoreTemplates/aurelia-spa#7]
In the instructions, it says to run the following:

> dotnet tool install -g x

What's this "x" tool? I can't find any information about it.

**Comment by mythz** [comment]
Docs are available on https://docs.servicestack.net
 - https://docs.servicestack.net/dotnet-new
 - https://docs.servicestack.net/dotnet-tool
 - https://docs.servicestack.net/mix-tool
